FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# PWP

Polls is a simple API allowing consumers to view polls and vote in them.

## Recipes Collection [/recipes]

### List All Recipes [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Recipe [POST]

You may create new recipe using this action.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            

## Meals Collection  [/meals]

### List All Meals [GET]

+ Response 200 (application/json)

        [
        ]

### Create a New Meal [POST]

+ Request (application/json)

        [
        ]

+ Response 201 (application/json)
    
    + Headers
        
        Location: /meals/2
        
    + Body
        
        [
        ]